### ISSUE TITLE
RST-dt data format

### ISSUE THREAD

**Issue by metabolean5** [grig-guz/rst-coref#2]
Hi,
Thank you for the great repo,

I am planning on using your parser for some experiences with new RST data.

I wanted to know what formats (.dis, rs3 etc) of the RST-DT files am I suppose to use in these directories 

data/data_dir/train_dir/*
data/data_dir/test_dir/*

Thanks !

**Comment by grig-guz** [comment]
Hi, you will need files in .dis format. I don't remember at the moment if you need other files (.text, .edu) from RST-DT, you can try running the code as per README to see what is required.

**Comment by metabolean5** [comment]
Thanks ! I will try that.
