### ISSUE TITLE
action/relation maps, coreference clusters and train/dev split

### ISSUE THREAD

**Issue by arantzadev** [grig-guz/rst-coref#3]
Hi thanks for the repo!

I beleive I am almost done setting up your parser but I am stuck at the second step for peparing the data:
Upon running 
```
python main.py --prepare --train_dir ../data/data_dir/train_dir/ --pretrained_coref_path  
```
Using  the pretrained_coref_model.pt downloaded from the link you provide, I get the following error : 

rst-coref-master/src/data_helper.py", line 87, in create_data_helper 
    self.all_clusters.append(coref_trainer.predict_rst(doc)[0])
AttributeError: 'Trainer' object has no attribute 'predict_rst'

It is worth noting that i previously removed the argument ''higher_order=True" in the CorefScore constructor since : 

File "main.py", line 115, in <module>
    coref_model = CorefScore(higher_order=True).to(config[DEVICE])

Is there anything that I am missing in the installation of the coref resolver ?

Thank you in advance

**Comment by grig-guz** [comment]
Hi,
Can you try replacing "predict_rst" with "predict_clusters"?

**Comment by arantzadev** [comment]
thank you this worked perfectly
